### ISSUE TITLE
更新 webpack 之后测试和 CI 都通不过了

### ISSUE THREAD

**Issue by yuche** [mc-zone/remove-defineproperty-webpack-plugin#1]
重现：
https://travis-ci.org/yuche/remove-defineproperty-webpack-plugin/jobs/288588627
这是未经修改的一个 fork。

直接 clone 下来 npm/yarn install 也跑不通测试，奇怪的地方在于即便把 webpack 换成 3.3.0 也不行。

**Comment by mc-zone** [comment]
合了下webpack 3.8.1的修改，修复了，你用0.0.3试试
